{
  "template": [
    "<!DOCTYPE html>",
    "<html>",
    "",
    "<head>",
    "    <meta name=\"viewport\" content=\"width=device-width,",
    "                                initial-scale=1.0, user-scalable=yes\">",
    "    <meta charset=\"utf-8\">",
    "    <title>",
    "        {title} - Tinellb.com",
    "    </title>",
    "    {stylesheets: basic_style.css style.css}",
    "    {icon: favicon.png}",
    "    {search-script}",
    "</head>",
    "",
    "<body>",
    "    <flex>",
    "        <nav-pane>",
    "            {links: family}",
    "        </nav-pane>",
    "        <content>",
    "            {nav-footer}",
    "            {heading: title}",
    "            {main-contents}",
    "            {nav-footer}",
    "            <copyright>",
    "                <no-breaks>",
    "                    {copyright: &copy;2017-%Y <a href=\"http://www.tinellb.com/about.html\">Ryan Eakins</a>.}",
    "                </no-breaks>",
    "                <copyright>",
    "                    {copyright: Last updated: %A, %B %#d%t, %Y.}",
    "                </copyright>",
    "            </copyright>",
    "        </content>",
    "    </flex>",
    "    <script type=\"text/javascript\">",
    "        for (elt of document.getElementsByClassName('javascript')) {",
    "            elt.style.display = \"block\";",
    "        }",
    "    </script>",
    "    {scripts}",
    "</body>",
    "",
    "</html>",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  "styles": {}
}